<span style="font-size: 45px"> Machine Learning </span> <span style="font-size: 25px; color: yellow"> for Dummies</span>

<span style="font-size: 30px"> Part 2: </span> <span style="font-size: 30px; color: green"> Preparing Your Learning Tools</span>

<span style="font-size: 20px"> Chapter 4: </span> <span style="font-size: 20px; color: skyblue"> Installing a Python Distribution </span>

In [56]:
# libraries
import pyarrow.feather as feather # read from file

# read from file
read_df = feather.read_feather('./datasets-master/air_passengers.feather')

# print it
print(read_df)

       Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]


In [57]:
# show DataFrame
read_df

Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

<span style="font-size: 20px"> Chapter 5: </span> <span style="font-size: 20px; color: skyblue"> Beyond Basic Coding in Python </span>

In [58]:
# WORKING WITH FUNCTIONS - CREATING REUSABLE FUNCTION


# defining a function
def sayHello():
    return "Hello There!"

# CALLING FUNCTIONS
sayHello()

'Hello There!'

In [59]:
# DEFINING A FUNCTION WITH PARAMETERS

def DoSum(Value1, Value2):
    return Value1 + Value2

# calling the fuction with integers
DoSum(1, 2)

3

In [60]:
# DEFINING FUCTION WITH PARAMETERS AND CALLING IT WITH KEYWORDS (SEDING ARGUMENTS BY KEYWORD)

def DisplaySum(Value1, Value2):
    print(str(Value1) + ' + ' + str(Value2) + ' = ' + str((Value1 + Value2)))

# first testing it with positional arguments
DisplaySum(2, 3)

2 + 3 = 5


In [61]:
# now with keywords
DisplaySum(Value2 = 3, Value1= 2)

2 + 3 = 5


In [62]:
# GIVING FUNCTION ARGUMENTS A DEFAULT VALUE

def SayHello(Greeting = "No Value Supplied"):
    print(Greeting)

# calling the function without a value
SayHello()

No Value Supplied


In [63]:
# calling the fuction with a value
SayHello("Howdy!")

Howdy!


In [64]:
# CREATING FUNCTIONS WITH A VARIABLE NUMBER OF ARGUMENTS

def DisplayMulti(ArgCount = 0, *VarArgs):
    print('You passed ' + str(ArgCount) + ' arguments.', VarArgs)

# call the function
DisplayMulti()

You passed 0 arguments. ()


In [65]:
# call the function with arguments
DisplayMulti(3, 'Hello', 1, True)

You passed 3 arguments. ('Hello', 1, True)


In [66]:
# WORKING WITH MODULES

import os # working with files
os.getcwd() # current directory

# os.chdir('new_path') # change the directory so that Python looks in

# os.environ['PYTHONPATH'] # determine where Python looks for modules

'/home/marius/Desktop/PYTHON Projects/Machine-Learning-for-Dummies-Book-Practice'

In [67]:
# STORING DATA USING SETS, LISTS AND TUPLES

# SETS

SetA = set(['Red', 'Blue', 'Green', 'Black'])
SetB = set(['Black', 'Green', 'Yellow', 'Orange'])

# operations
SetX = SetA.union(SetB) # union A U B
SetY = SetA.intersection(SetB) # intersection
SetZ = SetA.difference(SetB) # A - B

# printing
print('{0}\n{1}\n{2}'.format(SetX, SetY, SetZ))

{'Red', 'Yellow', 'Orange', 'Blue', 'Green', 'Black'}
{'Green', 'Black'}
{'Red', 'Blue'}


In [68]:
# superset True of False (boolean)
print(SetA.issuperset(SetY))

True


In [69]:
# subset True or False (boolean)
print(SetA.issubset(SetX))

True


In [70]:
# add element in Set
SetA.add('Purple')

In [71]:
# verify subset condition
print(SetA.issubset(SetX))

False


In [72]:
# LISTS

# defining a list
ListA = [0, 1, 2, 3]
ListB = [4, 5, 6, 7]

# combined them
ListA.extend(ListB)

# print the list
print(ListA)

[0, 1, 2, 3, 4, 5, 6, 7]


In [73]:
# add value to list
ListA.append(-5)
print(ListA)

[0, 1, 2, 3, 4, 5, 6, 7, -5]


In [74]:
# remove value from list
ListA.remove(-5)
print(ListA)

[0, 1, 2, 3, 4, 5, 6, 7]


In [75]:
# combining lists using concatenation
ListX = ListA + ListB

# print the combined list
print(ListX)

[0, 1, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7]


In [76]:
# constructing lists using comprehensions
Letters = [letter.upper() for letter in 'Hello']

# print a list of letters in UpperCase
print(Letters)

['H', 'E', 'L', 'L', 'O']


In [77]:
# TUPLES

MyTuple = (1, 2, 3, (4, 5, 6, (7, 8, 9)))

# how does the nesting works
for Value1 in MyTuple:
    if type(Value1) == int:
        print(Value1)
    else:
        for Value2 in Value1:
            if type(Value2) == int:
                print('\t', Value2)
            else:
                for Value3 in Value2:
                    print('\t\t', Value3)

1
2
3
	 4
	 5
	 6
		 7
		 8
		 9


In [78]:
# adding new values
MyNewTuple = MyTuple.__add__((10, 11, 12, (13, 14, 15)))

# print the new tuple
print(MyNewTuple)

(1, 2, 3, (4, 5, 6, (7, 8, 9)), 10, 11, 12, (13, 14, 15))


In [79]:
# DEFINING USEFUL ITERATORS

ListA = ['Orange', 'Yellow', 'Green', 'Brown']
ListB = [1, 2, 3, 4]

# print the secondest color
print(ListA[1])


Yellow


In [80]:
# WORKING WITH RANGES

# slicing
print(ListB[1:3])

[2, 3]


In [81]:
# for loop
for Value in ListB[1: 3]:
    print(Value)

2
3


In [82]:
# print first 3 values
print(ListB[:3])

[1, 2, 3]


In [83]:
# ITERATING MULTIPLE LISTS USING ZIP

# process two lists in parallel
for Value1, Value2 in zip(ListA, ListB):
    print(Value1, '\t', Value2)

Orange 	 1
Yellow 	 2
Green 	 3
Brown 	 4


In [84]:
# WORKING WITH GENERATORS USING YIELD

def MyLetter():
    for Letter in Letters:
        yield Letter

# creating the Letters list
Letters = [letter.upper() for letter in 'Hello']

# create the object
ListIt = MyLetter()

# printing the object
print(next(ListIt))
print(next(ListIt))
print(next(ListIt))
print(next(ListIt))
print(next(ListIt))


H
E
L
L
O


In [85]:
# DICTIONARIES

MyDict = {'Orange': 1, 'Blue': 2, 'Pink': 3}

# storing and retrieving data 
print(MyDict['Pink'])

3


In [86]:
# see the keys
print(MyDict.keys())

dict_keys(['Orange', 'Blue', 'Pink'])


In [87]:
# see the values
print(MyDict.values())

dict_values([1, 2, 3])


<span style="font-size: 30px"> Part 3: </span> <span style="font-size: 30px; color: green"> Getting Started with the Math Basics</span>

<span style="font-size: 20px"> Chapter 7: </span> <span style="font-size: 20px; color: skyblue"> Demystifying the Math Behind Machine Learning </span>

In [88]:
# UNDERSTANDING SCALAR AND VECTOR OPERATIONS

# NumPy Library
import numpy as np

# 16 bit long value
myShort = np.short(15)
print(myShort, '\n')

15 



In [89]:
# creating a vector normally
myVect = np.array([1, 3, 5, 7, 9])
print(myVect, '\n')

[1 3 5 7 9] 



In [90]:
# arange
myVect = np.arange(1, 10, 2)
print(myVect, '\n')

[1 3 5 7 9] 



In [91]:
# specifying the data
myVect = np.array(np.int16([1.4, 2, 3, 4]))
print(myVect, '\n')

[1 2 3 4] 



In [92]:
# fill the vector with ones
myVect = np.ones(4)
print(myVect, '\n')

[1. 1. 1. 1.] 



In [93]:
# fill the vector with ones
myVect = np.zeros(4)
print(myVect, '\n')

[0. 0. 0. 0.] 



In [94]:
# MATH FUNCTIONS

myVect = np.array([1, 2, 3, 4])

# adds 1
print(myVect + 1, '\n') 

[2 3 4 5] 



In [95]:
# subtracts 1
print(myVect - 1, '\n') 

[0 1 2 3] 



In [96]:
# 2nd power
print(2 ** myVect, '\n') 

[ 2  4  8 16] 



In [97]:
# comparison operations
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a == b, '\n')
print(a < b, '\n')

[False  True False  True] 

[ True False  True False] 



In [98]:
# logical operations
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a, b), '\n')
print(np.logical_and(a, b), '\n')
print(np.logical_not(a), '\n')
print(np.logical_xor(a, b), '\n')

[ True  True  True False] 

[ True False False False] 

[False  True False  True] 

[False  True  True False] 



In [99]:
# PERFORMING VECTOR MULTIPLICATION

myVect = np.array([1, 2, 3, 4])

print(myVect * myVect)

[ 1  4  9 16]


In [100]:
# dot product
myVect.dot(myVect)

30

In [101]:
# CREATING A MATRIX

# UNDERSTANDING BASIC OPERATIONS

# substraction
A = np.array([[1, 1], [1, 0]])
B = np.array([[1, 0], [0, 1]])

C = A - B
print(C)

[[ 0  1]
 [ 1 -1]]


In [102]:
# multiply the resulting matrix
print(C * -2)

[[ 0 -2]
 [-2  2]]


In [103]:
# performing matrix multiplication
X = np.array([[4, 5], [2, 4], [3, 3]])
b = [3, -2]
print(X @ b)

[ 2 -2  3]


In [104]:
# explication
print(sum([4*3, 5*-2]))
print(sum([2*3, 4*-2]))
print(sum([3*3, 3*-2]))

2
-2
3


In [105]:
# y = Xb
B = np.array([[3, -2], [-2, 5]])
print(X @ b) 

[ 2 -2  3]


In [106]:
# GLACING AT ADVANCED MATRIX OPERATIONS

# transposition
A = np.array([[1, 2, 3], [2, 3, 5], [7, 11, 13]])
print(A.transpose())

[[ 1  2  7]
 [ 2  3 11]
 [ 3  5 13]]


In [107]:
# inverse of matrix A
print(np.linalg.inv(A))

[[-3.2  1.4  0.2]
 [ 1.8 -1.6  0.2]
 [ 0.2  0.6 -0.2]]


In [108]:
# USING VECTORIZATION EFFECTIVELY

# create ndarray arrays of multiple dimensions
y = np.array([44, 21, 37])
print(y)
# shape of the matrix
print(y.shape)

[44 21 37]
(3,)


In [109]:
# create matrices made of rows and columns by using list of lists
X = np.array([[1.1, 1, 545, 1], [4.6, 0, 345, 2], [7.2, 1, 754, 3]])
print(X)

[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


In [110]:
# reshape a single list matrix
X = np.array([1.1, 1, 545, 1, 4.6, 0, 345, 2, 7.2, 1, 754, 3]).reshape(3, 4)
print(X)

[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


<span style="font-size: 20px"> Chapter 9: </span> <span style="font-size: 20px; color: skyblue"> Validating Machine Learning </span>

In [123]:
# LOOKING FOR ALTERNATIVES IN VALIDATION

# bootstrapping
n = 1000
results = list()

for j in range(10000):
    chosen = np.random.randint(0, n, size = n)
    results.append(len(np.unique(chosen)) / n)

avg_oob = 1 - np.mean(results)
print(f"Avg out-of-bootstrap: {avg_oob * 100 : 0.3}%")

Avg out-of-bootstrap:  36.8%
